server:
  servlet:
    context-path: /cnt-springboot

sngenerator:
  generators: first,second,third
  first: 
    bean-name: firstSn
    init-num: 10000
    step: 1
    max-num: 0
  second:
    bean-name: secondSn
    init-num: 1000
    step: 1
    max-num: 0
  third: 
    bean-name: thirdSn
    init-num: 100
    step: 1
    max-num: 0
    
groupsngenerator:
  generators: first,second,third
  first: 
    bean-name: gfirstSn
    init-num: 10000
    step: 1
    max-num: 0
  second:
    bean-name: gsecondSn
    init-num: 1000
    step: 1
    max-num: 0
  third: 
    bean-name: gthirdSn
    init-num: 100
    step: 1
    max-num: 0

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 3000
