server:
  servlet:
    context-path: /cnt-springboot

idgenerator:
  generators: first,second,third
  first:
    bean-name: firstId
    base-time: 2019-01-01
    node-bits: 3
    node-num: ${nodeNum:0}
    cycle-bits: 16
  second:
    bean-name: secondId
    base-time: 2019-03-01
    node-bits: 3
    node-num: ${nodeNum:0}
    cycle-bits: 16
  third:
    bean-name: thirdId
    base-time: 2019-05-01
    node-bits: 3
    node-num: ${nodeNum:0}
    cycle-bits: 16
    
sngenerator:
  generators: first,second,third
  first: 
    bean-name: first
    init-num: 10000
    step: 1
    max-num: 0
  second:
    bean-name: second
    init-num: 1000
    step: 1
    max-num: 0
  third: 
    bean-name: third
    init-num: 100
    step: 1
    max-num: 0
    
groupsngenerator:
  generators: first,second,third
  first: 
    bean-name: gfirst
    init-num: 10000
    step: 1
    max-num: 0
  second:
    bean-name: gsecond
    init-num: 1000
    step: 1
    max-num: 0
  third: 
    bean-name: gthird
    init-num: 100
    step: 1
    max-num: 0

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 3000
